[features]
seeds = false
skip-lint = false
[programs.devnet]
sixteen_personalities = "2sZ2p39s4wTQrVteV8XP5r8d8cbqr2pdQnpvU3BvcbkK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mateo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
