[features]
seeds = false
skip-lint = false
[programs.devnet]
sixteen_personalities = "BDsVGnwVTjjV93wSjttonsXWLt4Sj1Ec6thTKsciQXgD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mateo/.config/solana/id.json"

[scripts]
test_me = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/SixteenPersonalities.ts"
